openapi: 3.0.1
info:
  title: API pour l'entité Affectation
  version: 1.0.0
components:
  schemas:
    AffectationDto:
      type: object
      properties:
        employe:
          $ref: 'employe.yaml#/components/schemas/EmployesRep'
        projet:
          $ref: 'projet.yaml#/components/schemas/ProjetResponse'
        dateDebut:
          type: string
          format: date
        dateFin:
          type: string
          format: date

    AffectationResponse:
      allOf:
        - $ref: '#/components/schemas/AffectationDto'
        - type: object
          properties:
            id_affectation:
              type: integer
      description: Toutes les propriétés de l'entité affectation.