openapi: 3.0.1
info:
  title: API pour l'entité Client
  version: 1.0.0
paths:
  /clients:
    post:
      tags:
        - Clients
      summary: Enregistrement des clients
      operationId: saveClient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientDto'
            examples:
              ClientDto:
                summary: Exemple d'ajout d'un client
                value:
                  nom_client: MCN
                  adresse: boul Rene Levesque
                  siteweb: mcn.gouv.qc
                  description: gouvernement Malagasy
                  email: test@gmail.com
      responses:
        '201':
          description: Ajout success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientDto'
        '500':
          description: Erreur interne du serveur

    get:
      summary: Récupérer la liste des toutes les clients disponibles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClientDto'
        '500':
          description: Erreur interne du serveur

  /clients/{client_id}:
    get:
      summary: Obtenir un client par ID
      description: Récupère un client spécifique en fonction de son ID.
      parameters:
        - name: client_id
          in: path
          description: ID du client à récupérer
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Succès - Ressource récupérée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientDto'
        '404':
          description: Ressource non trouvée
        '500':
          description: Erreur interne du serveur

    put:
      summary: Mettre à jour la table client
      parameters:
        - name: client_id
          in: path
          description: ID du client à mettre à jour'
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientDto'
      responses:
        '200':
          description: Client mis à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientDto'
        '404':
          description: Client non trouvé
        '500':
          description: Erreur interne du serveur

    delete:
      summary: Supprimer un client par ID
      description: Supprime un exemple en utilisant son ID comme paramètre
      parameters:
        - name: client_id
          in: path
          description: ID du client à supprimer
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Aucun contenu
        '404':
          description: client non trouvé
components:
  schemas:

    #request and response pour l'employe
    ClientDto:
      type: object
      required:
        - nom_client
      properties:
        id_client:
          type: integer
        nom_client:
          type: string
        adresse:
          type: string
        siteweb:
          type: string
        description:
          type: string
        email:
          type: string

  #   ClientResponse:
  #      allOf:
  #        - $ref: '#/components/schemas/ClientDto'
  #        - type: object
  #          properties:
  #            id_client:
  #              type: integer
  #      description: Liste de toutes les clients.
 