openapi: 3.0.1
info:
  title: API pour l'entité Client
  version: 1.0.0
components:
  schemas:

    #request and response pour l'employe
    ClientDto:
      type: object
      required:
        - nom_client
      properties:
        id_client:
          type: integer
        nom_client:
          type: string
        adresse:
          type: string
        siteweb:
          type: string
        description:
          type: string
        email:
          type: string

  #   ClientResponse:
  #      allOf:
  #        - $ref: '#/components/schemas/ClientDto'
  #        - type: object
  #          properties:
  #            id_client:
  #              type: integer
  #      description: Liste de toutes les clients.
 