openapi: 3.0.1
info:
  title: API pour l'entité Client
  version: 1.0.0
components:
  schemas:

    #request params
    ClientDto:
      type: object
      required:
        - nom_client
      properties:
        nom_client:
          type: string
        adresse:
          type: string
        siteweb:
          type: string
        description:
          type: string
        email:
          type: string

      #Response
    ClientResponse:

      allOf:
        - $ref: '#/components/schemas/ClientDto'
        - type: object
          properties:
            id_client:
              type: integer
      description:  Toutes les propriétés du client.
 