openapi: 3.0.1
info:
  title: Affectation Fujitsu
  description: Mini projet pour les affectations des employés.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: dev
tags:
  - name: Employes
    description: Tags pour l'employe
paths:
  /employes:
    post:
      tags:
        - Employes
      summary: Enregistrer les employeurs
      operationId: saveEmployer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeReq'
            examples:
              UtilisateurReq:
                summary: Enregistrement d'un employé
                value:
                  nom: Christian
                  prenom: Thierry
                  adresse: 200 av pont scott
                  nationalite: malagasy
                  email: test@gmail.com
                  specialiste: JAVA
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeReq'
        '500':
          description: Erreur interne du serveur

    get:
      summary: Récupérer la liste des toutes les employes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EmployesRep'
        '500':
          description: Erreur interne du serveur
          
  /employes/{employe_id}:
    get:
      summary: Obtenir un employe par ID
      description: Récupère un employe spécifique en fonction de son ID.
      parameters:
        - name: employe_id
          in: path
          description: ID de l'employe à récupérer
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Succès - Ressource récupérée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployesRep'
        '404':
          description: Ressource non trouvée
        '500':
          description: Erreur interne du serveur          

    put:
      summary: Mettre à jour la table employe
      description: Mettre à jour les informations existant
      parameters:
        - name: employe_id
          in: path
          description: ID de l'employé'
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeReq'
      responses:
        '200':
          description: Employe mis à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeReq'
        '404':
          description: Employe non trouvé
        '500':
          description: Erreur interne du serveur

    delete:
      summary: Supprimer un employe par ID
      description: Supprime un exemple en utilisant son ID comme paramètre
      parameters:
        - name: employe_id
          in: path
          description: ID de l'employe à supprimer
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Aucun contenu
        '404':
          description: employe non trouvé    
components:
  schemas:
    EmployeReq:
      type: object
      required:
        - nom
        - adresse
        - nationalite
        - email
        - phone
        - date_embauche
        - specialite
      properties:
        nom:
          type: string
        prenom:
          type: string
        adresse:
          type: string
        nationalite:
          type: string
        email:
          type: string
        phone:
          type: string
        date_embauche:
          type: string
        specialite:
          type: string
        description:
          type: string
        photo:
          type: string
        cv:
          type: string            
     
    EmployesRep:
      allOf:
        - $ref: '#/components/schemas/EmployeReq'
        - type: object
          properties:
            id_employe:
              type: integer
      description: Toutes les employés.
 