openapi: 3.0.1
info:
  title: Affectation Fujitsu
components:
  schemas:
    #request and response pour l'employe
    EmployeReq:
      type: object
      required:
        - nom
        - adresse
        - nationalite
        - email
        - phone
        - specialite
      properties:
        nom:
          type: string
          minLength: 2
          maxLength: 5
          example: Vincent
        prenom:
          type: string
        adresse:
          type: string
        nationalite:
          type: string
        email:
          type: string
        phone:
          type: string
        date_embauche:
          type: string
          format: date
        specialite:
          type: string
        description:
          type: string
        photo:
          type: string
        cv:
          type: string
    EmployesRep:
      allOf:
        - $ref: '#/components/schemas/EmployeReq'
        - type: object
          properties:
            id_employe:
              type: integer
      description: Toutes les employés.
 