openapi: 3.0.1
info:
  title: API pour l'entité Projet
components:
  schemas:

    ProjetDto:
      type: object
      required:
        - code_projet
      properties:
        id_projet:
          type: integer
        code_projet:
          type: string
        nom_projet:
          type: string
        description:
          type: string
        client:
          $ref: 'client.yaml#/components/schemas/ClientDto'